import type { CourseSpec, HoleSpec, Dogleg, HazardStyle } from './types'
import { OSM_GEOMETRY } from './geometry'
import { PLAY_RATINGS } from './playRatings'

type Row = [3 | 4 | 5, number, number, Dogleg, HazardStyle, string?, boolean?]

function holes(rows: Row[]): HoleSpec[] {
  return rows.map(([par, yards, strokeIndex, dogleg, hazard, signature, island], i) => ({
    number: i + 1,
    par,
    yards,
    strokeIndex,
    dogleg,
    hazard,
    signature,
    island,
  }))
}

export const COURSES: CourseSpec[] = [
  // Course order is the daily rotation schedule (COURSES[(puzzle-1) % 49]).
  // Curated for launch: marquee openers, and the five toughest courses spaced
  // well apart so brutal days never cluster.
  {
    slug: 'pebble-beach',
    name: 'Pebble Beach Links',
    location: 'Pebble Beach, California',
    difficulty: 8,
    greens: 'Fast',
    wind: 15,
    blurb: 'Cliffs, the Pacific, and the greatest closing stretch in the game.',
    holes: holes([
      [4, 380, 8, 'R', 'none'],
      [5, 502, 12, 'R', 'sand'],
      [4, 390, 6, 'L', 'sand'],
      [4, 331, 16, 'S', 'ocean'],
      [3, 188, 14, 'S', 'ocean'],
      [5, 506, 4, 'R', 'sand'],
      [3, 106, 18, 'S', 'ocean', 'The tiny cliff par 3 — a flick of wedge over the Pacific'],
      [4, 418, 2, 'R', 'ocean', 'The second shot over the chasm — one of golf’s great forced carries'],
      [4, 462, 10, 'S', 'ocean'],
      [4, 446, 5, 'R', 'ocean'],
      [4, 380, 9, 'S', 'sand'],
      [3, 188, 17, 'S', 'none'],
      [4, 399, 7, 'L', 'sand'],
      [5, 572, 13, 'R', 'sand'],
      [4, 396, 3, 'L', 'sand'],
      [4, 402, 1, 'L', 'sand'],
      [3, 178, 15, 'S', 'ocean'],
      [5, 543, 11, 'L', 'ocean', 'Home along the shoreline — the finest finishing hole in the game'],
    ]),
  },
  {
    slug: 'st-andrews-old',
    name: 'St Andrews — Old Course',
    location: 'St Andrews, Scotland',
    difficulty: 7,
    greens: 'Firm',
    wind: 20,
    blurb: 'The Home of Golf — double greens, the Swilcan Bridge, and Hell Bunker.',
    holes: holes([
      [4, 376, 10, 'S', 'none', 'The Swilcan Burn guards the widest fairway in golf'],
      [4, 453, 6, 'S', 'sand'],
      [4, 397, 14, 'S', 'sand'],
      [4, 480, 4, 'S', 'sand'],
      [5, 568, 12, 'S', 'sand'],
      [4, 412, 8, 'S', 'sand'],
      [4, 371, 2, 'S', 'sand'],
      [3, 175, 16, 'S', 'sand'],
      [4, 352, 18, 'S', 'none'],
      [4, 386, 9, 'S', 'none'],
      [3, 174, 15, 'S', 'sand'],
      [4, 348, 11, 'S', 'sand'],
      [4, 465, 5, 'S', 'sand'],
      [5, 618, 13, 'S', 'sand', 'Mind Hell Bunker — it swallows the greedy on the Long hole'],
      [4, 455, 3, 'S', 'sand'],
      [4, 423, 7, 'S', 'sand'],
      [4, 495, 1, 'R', 'sand', 'The Road Hole — over the sheds, and beware the road behind'],
      [4, 357, 17, 'S', 'none', 'Home over the Swilcan Bridge to the Valley of Sin'],
    ]),
  },
  {
    slug: 'augusta-national',
    name: 'Augusta National',
    location: 'Augusta, Georgia',
    difficulty: 9,
    greens: 'Fast',
    wind: 6,
    blurb: 'Cathedral pines, wicked greens, and the most famous back nine in golf.',
    holes: holes([
      [4, 445, 9, 'R', 'sand'],
      [5, 575, 11, 'L', 'sand'],
      [4, 350, 17, 'S', 'sand'],
      [3, 240, 3, 'S', 'sand'],
      [4, 495, 1, 'L', 'sand'],
      [3, 180, 15, 'S', 'none'],
      [4, 450, 7, 'S', 'sand'],
      [5, 570, 13, 'L', 'sand'],
      [4, 460, 5, 'L', 'sand'],
      [4, 495, 4, 'L', 'sand'],
      [4, 520, 2, 'L', 'water', 'White Dogwood — Amen Corner opens with water lurking left'],
      [3, 155, 18, 'S', 'water', 'Golden Bell — the treacherous little par 3 over Rae’s Creek'],
      [5, 545, 14, 'L', 'water', 'Azalea — bend it round the creek, then dare the second'],
      [4, 440, 8, 'S', 'none'],
      [5, 550, 12, 'S', 'water'],
      [3, 170, 16, 'S', 'water', 'Redbud — skip it down the slope toward a Sunday flag'],
      [4, 440, 10, 'S', 'sand'],
      [4, 465, 6, 'R', 'sand'],
    ]),
  },
  {
    slug: 'tpc-sawgrass',
    name: 'TPC Sawgrass — Stadium',
    location: 'Ponte Vedra Beach, Florida',
    difficulty: 9,
    greens: 'Fast',
    wind: 10,
    blurb: 'The Stadium Course — all roads lead to the island green at seventeen.',
    holes: holes([
      [4, 423, 9, 'S', 'water'],
      [5, 532, 13, 'R', 'water'],
      [3, 177, 15, 'S', 'water'],
      [4, 384, 5, 'R', 'sand'],
      [4, 471, 3, 'S', 'sand'],
      [4, 393, 7, 'L', 'water'],
      [4, 451, 1, 'L', 'sand'],
      [3, 237, 11, 'S', 'water'],
      [5, 583, 17, 'R', 'sand'],
      [4, 424, 6, 'S', 'sand'],
      [5, 558, 12, 'L', 'water'],
      [4, 358, 4, 'R', 'sand'],
      [3, 181, 16, 'S', 'sand'],
      [4, 481, 8, 'S', 'water'],
      [4, 449, 14, 'R', 'water'],
      [5, 523, 2, 'R', 'water', 'The reachable five before the island — seize your chance'],
      [3, 137, 18, 'S', 'water', 'The island green — all carry, no bailout', true],
      [4, 447, 10, 'L', 'water', 'Water hugs the left the whole way to the clubhouse'],
    ]),
  },
  {
    slug: 'harbour-town',
    name: 'Harbour Town Golf Links',
    location: 'Hilton Head Island, South Carolina',
    difficulty: 7,
    greens: 'Firm',
    wind: 12,
    blurb: 'Tight, tree-lined, and tactical, finishing at the candy-striped lighthouse.',
    holes: holes([
      [4, 414, 11, 'R', 'sand'],
      [5, 505, 9, 'S', 'water'],
      [4, 436, 7, 'L', 'sand'],
      [3, 200, 15, 'S', 'water'],
      [5, 535, 5, 'R', 'sand'],
      [4, 419, 3, 'L', 'water'],
      [3, 192, 17, 'S', 'water'],
      [4, 470, 1, 'R', 'sand'],
      [4, 337, 13, 'S', 'sand'],
      [4, 439, 8, 'L', 'water'],
      [4, 436, 6, 'S', 'sand'],
      [4, 451, 4, 'R', 'sand'],
      [4, 375, 12, 'L', 'water'],
      [3, 192, 16, 'S', 'water'],
      [5, 575, 10, 'R', 'water'],
      [4, 439, 2, 'L', 'sand'],
      [3, 185, 14, 'S', 'water'],
      [4, 472, 18, 'L', 'ocean', 'Into the wind to the candy-striped lighthouse'],
    ]),
  },
  {
    slug: 'carnoustie',
    name: 'Carnoustie — Championship',
    location: 'Carnoustie, Scotland',
    difficulty: 10,
    greens: 'Firm',
    wind: 18,
    blurb: 'They call it Car-nasty for a reason — the meanest finish in championship golf.',
    holes: holes([
      [4, 401, 10, 'S', 'none'],
      [4, 435, 4, 'R', 'sand'],
      [4, 345, 14, 'L', 'sand'],
      [4, 375, 16, 'S', 'water'],
      [4, 387, 12, 'R', 'sand'],
      [5, 520, 2, 'L', 'sand', 'Hogan’s Alley — thread between the out-of-bounds and the bunkers'],
      [4, 394, 8, 'S', 'sand'],
      [3, 167, 18, 'S', 'sand'],
      [4, 416, 6, 'R', 'sand'],
      [4, 446, 3, 'S', 'sand'],
      [4, 362, 15, 'S', 'sand'],
      [5, 479, 9, 'L', 'water'],
      [3, 161, 17, 'S', 'sand'],
      [5, 476, 1, 'R', 'sand'],
      [4, 459, 7, 'S', 'sand'],
      [3, 245, 13, 'S', 'sand'],
      [4, 433, 5, 'L', 'water', 'The Island — the Barry Burn snakes across again and again'],
      [4, 444, 11, 'S', 'water', 'Home over the Barry Burn — where Opens slip away'],
    ]),
  },
  {
    slug: 'copper-canyon',
    name: 'Copper Canyon',
    location: 'Scottsdale, Arizona',
    difficulty: 5,
    greens: 'Medium',
    wind: 6,
    blurb: 'Desert target golf. Green ribbons through red rock and cactus.',
    holes: holes([
      [4, 372, 11, 'S', 'sand'],
      [4, 419, 5, 'R', 'sand'],
      [3, 183, 13, 'S', 'sand'],
      [5, 547, 7, 'L', 'sand', 'A dry wash splits the layup zone'],
      [4, 402, 3, 'S', 'sand'],
      [4, 341, 17, 'R', 'none', 'Drivable if you flirt with the saguaros'],
      [3, 217, 9, 'S', 'sand'],
      [4, 433, 1, 'L', 'sand', 'The canyon squeezes the drive to a ribbon'],
      [5, 561, 15, 'S', 'sand'],
      [4, 386, 12, 'R', 'sand'],
      [3, 149, 18, 'S', 'none'],
      [4, 441, 2, 'S', 'sand'],
      [5, 528, 14, 'R', 'sand'],
      [4, 397, 8, 'L', 'sand'],
      [4, 424, 4, 'S', 'sand'],
      [3, 192, 16, 'S', 'sand'],
      [4, 409, 10, 'R', 'sand'],
      [5, 539, 6, 'L', 'sand', 'Sunset finisher between two mesas'],
    ]),
  },
  {
    slug: 'royal-portrush-dunluce',
    name: 'Royal Portrush — Dunluce Links',
    location: 'Portrush, Northern Ireland',
    difficulty: 9,
    greens: 'Firm',
    wind: 20,
    blurb: 'Dunes and drama on the Antrim coast, home of Calamity Corner.',
    holes: holes([
      [4, 420, 7, 'S', 'sand'],
      [5, 575, 11, 'R', 'sand'],
      [3, 176, 15, 'S', 'sand'],
      [4, 502, 1, 'L', 'sand'],
      [4, 372, 13, 'R', 'ocean', 'White Rocks — the beach and the sea wait behind the green'],
      [3, 193, 9, 'S', 'ocean'],
      [5, 607, 5, 'L', 'sand'],
      [4, 434, 3, 'S', 'sand'],
      [4, 432, 17, 'R', 'sand'],
      [4, 373, 12, 'S', 'sand'],
      [4, 475, 2, 'L', 'sand'],
      [5, 532, 16, 'R', 'sand'],
      [3, 199, 14, 'S', 'sand'],
      [4, 466, 4, 'S', 'sand'],
      [4, 429, 8, 'L', 'sand'],
      [3, 236, 6, 'S', 'sand', 'Calamity Corner — a long iron over a yawning chasm'],
      [4, 409, 10, 'R', 'sand'],
      [4, 474, 18, 'S', 'sand'],
    ]),
  },
  {
    slug: 'cypress-point',
    name: 'Cypress Point',
    location: 'Pebble Beach, California',
    difficulty: 8,
    greens: 'Fast',
    wind: 12,
    blurb: 'Where the Monterey pines meet the sea for the most beautiful stretch in golf.',
    holes: holes([
      [4, 421, 1, 'S', 'sand'],
      [5, 548, 3, 'S', 'sand'],
      [3, 162, 7, 'S', 'sand'],
      [4, 384, 9, 'R', 'sand'],
      [5, 493, 15, 'S', 'none'],
      [5, 518, 11, 'R', 'sand'],
      [3, 168, 5, 'S', 'sand'],
      [4, 363, 13, 'L', 'none'],
      [4, 292, 17, 'S', 'sand'],
      [5, 480, 18, 'S', 'sand'],
      [4, 437, 4, 'S', 'none'],
      [4, 404, 6, 'L', 'none'],
      [4, 365, 14, 'R', 'sand'],
      [4, 388, 10, 'S', 'sand'],
      [3, 139, 12, 'S', 'ocean', 'The little sister — a short poke across the cove'],
      [3, 231, 2, 'S', 'ocean', 'The great ocean carry — 200-plus yards of Pacific to clear'],
      [4, 393, 8, 'L', 'ocean', 'Around the headland — the drive flirts with the cliffs'],
      [4, 346, 16, 'S', 'sand'],
    ]),
  },
  {
    slug: 'whistling-straits',
    name: 'Whistling Straits — Straits',
    location: 'Sheboygan, Wisconsin',
    difficulty: 9,
    greens: 'Firm',
    wind: 18,
    blurb: 'Pete Dye’s faux-Irish links along Lake Michigan with a thousand bunkers.',
    holes: holes([
      [4, 408, 11, 'S', 'sand'],
      [5, 593, 7, 'S', 'sand'],
      [3, 181, 15, 'S', 'water'],
      [4, 489, 1, 'L', 'sand'],
      [5, 569, 9, 'R', 'sand'],
      [4, 355, 13, 'S', 'sand'],
      [3, 221, 5, 'S', 'water', 'Shipwreck — a par 3 perched above Lake Michigan'],
      [4, 507, 3, 'S', 'sand'],
      [4, 446, 17, 'S', 'water'],
      [4, 361, 12, 'S', 'sand'],
      [5, 618, 8, 'S', 'sand'],
      [3, 143, 18, 'S', 'water'],
      [4, 404, 14, 'S', 'sand'],
      [4, 372, 10, 'S', 'sand'],
      [4, 518, 2, 'L', 'sand'],
      [5, 569, 6, 'R', 'sand'],
      [3, 223, 4, 'S', 'water', 'Pinched Nerve — 220 yards along the water with it all on the line'],
      [4, 520, 16, 'L', 'sand', 'Dyeabolical — Pete Dye’s long, cruel last word'],
    ]),
  },
  {
    slug: 'tpc-potomac',
    name: 'TPC Potomac at Avenel Farm',
    location: 'Potomac, Maryland',
    difficulty: 8,
    greens: 'Fast',
    wind: 9,
    blurb: 'A tight, penal tour stop where accuracy beats power every time.',
    holes: holes([
      [4, 440, 3, 'R', 'sand'],
      [5, 619, 11, 'L', 'water'],
      [3, 225, 13, 'S', 'sand'],
      [4, 440, 7, 'S', 'water'],
      [4, 365, 17, 'R', 'sand'],
      [4, 484, 1, 'L', 'water'],
      [4, 452, 5, 'S', 'sand'],
      [4, 467, 9, 'R', 'water'],
      [3, 201, 15, 'S', 'sand'],
      [5, 560, 8, 'R', 'water'],
      [4, 470, 2, 'L', 'water'],
      [3, 168, 14, 'S', 'water'],
      [4, 360, 16, 'S', 'sand'],
      [4, 299, 18, 'R', 'water', 'Drivable and dangerous — water dares the bold to have a go'],
      [4, 490, 4, 'R', 'water'],
      [4, 412, 10, 'R', 'sand'],
      [3, 190, 12, 'S', 'water'],
      [4, 465, 6, 'R', 'water'],
    ]),
  },
  {
    slug: 'gullwing-point',
    name: 'Gullwing Point',
    location: 'Mendocino, California',
    difficulty: 7,
    greens: 'Firm',
    wind: 14,
    blurb: 'Clifftop golf where every right miss is the Pacific.',
    holes: holes([
      [4, 388, 9, 'S', 'sand'],
      [5, 527, 13, 'R', 'sand'],
      [4, 421, 3, 'R', 'ocean', 'The fairway tilts toward the cliff the whole way'],
      [3, 152, 17, 'S', 'ocean', 'Short but knee-knocking — nothing but surf long'],
      [4, 442, 1, 'R', 'ocean'],
      [4, 366, 11, 'L', 'sand'],
      [5, 561, 7, 'R', 'ocean', 'Three shots along the bluff, or two brave ones'],
      [3, 201, 15, 'S', 'sand'],
      [4, 409, 5, 'S', 'sand'],
      [4, 353, 16, 'L', 'sand'],
      [3, 176, 12, 'S', 'ocean'],
      [4, 431, 2, 'R', 'ocean', 'The chasm carry — the card turns here'],
      [5, 538, 10, 'L', 'sand'],
      [4, 397, 8, 'S', 'sand'],
      [4, 415, 4, 'R', 'ocean'],
      [3, 139, 18, 'S', 'sand'],
      [4, 380, 14, 'L', 'sand'],
      [5, 549, 6, 'R', 'ocean', 'Home along the point — birdie or heartbreak'],
    ]),
  },
  {
    slug: 'seminole',
    name: 'Seminole Golf Club',
    location: 'Juno Beach, Florida',
    difficulty: 9,
    greens: 'Fast',
    wind: 16,
    blurb: 'Ross by the sea in Florida, a Donald Ross favorite ringed by ocean wind.',
    holes: holes([
      [4, 405, 17, 'S', 'sand'],
      [4, 480, 5, 'L', 'water'],
      [5, 555, 13, 'R', 'sand'],
      [4, 495, 1, 'L', 'sand'],
      [3, 205, 15, 'S', 'sand'],
      [4, 390, 7, 'S', 'sand', 'The famous sixth — a diagonal wall of sand splits the fairway'],
      [4, 430, 3, 'R', 'sand'],
      [3, 225, 9, 'S', 'sand'],
      [5, 545, 11, 'L', 'water'],
      [4, 425, 12, 'S', 'sand'],
      [4, 465, 2, 'L', 'water'],
      [4, 370, 8, 'R', 'water'],
      [3, 170, 18, 'S', 'sand'],
      [5, 510, 14, 'L', 'water'],
      [5, 555, 10, 'R', 'water'],
      [4, 410, 4, 'R', 'water'],
      [3, 185, 16, 'S', 'sand'],
      [4, 445, 6, 'L', 'sand', 'Into the ocean wind for home — Ross saved his teeth for last'],
    ]),
  },
  {
    slug: 'birchwood-national',
    name: 'Birchwood National',
    location: 'Grand Rapids, Michigan',
    difficulty: 6,
    greens: 'Firm',
    wind: 8,
    blurb: 'Cathedral pines, white sand, greens like upturned saucers.',
    holes: holes([
      [4, 411, 6, 'R', 'sand'],
      [5, 552, 12, 'L', 'sand', 'A long five through the pines'],
      [4, 384, 10, 'S', 'sand'],
      [3, 197, 8, 'S', 'sand'],
      [4, 439, 2, 'L', 'sand'],
      [4, 368, 16, 'S', 'none'],
      [5, 517, 14, 'R', 'sand'],
      [3, 158, 18, 'S', 'sand'],
      [4, 427, 4, 'S', 'sand'],
      [4, 393, 9, 'L', 'sand'],
      [3, 221, 5, 'S', 'sand', 'The crowned green repels anything timid'],
      [4, 446, 1, 'R', 'sand', 'The National — nothing but perfect will do'],
      [4, 375, 15, 'S', 'none'],
      [5, 568, 11, 'L', 'sand'],
      [4, 405, 7, 'R', 'sand'],
      [3, 166, 17, 'S', 'sand'],
      [4, 431, 3, 'S', 'sand'],
      [5, 536, 13, 'R', 'sand', 'The amphitheater finish under the clubhouse oaks'],
    ]),
  },
  {
    slug: 'torrey-pines-south',
    name: 'Torrey Pines — South',
    location: 'La Jolla, California',
    difficulty: 9,
    greens: 'Firm',
    wind: 12,
    blurb: 'Long clifftop municipal that hosts majors above the Pacific.',
    holes: holes([
      [4, 452, 11, 'S', 'sand'],
      [4, 389, 13, 'R', 'sand'],
      [3, 198, 15, 'S', 'ocean', 'A clifftop par 3 with the Pacific shimmering far below'],
      [4, 488, 3, 'L', 'ocean'],
      [4, 453, 7, 'S', 'sand'],
      [5, 560, 9, 'R', 'ocean'],
      [4, 462, 5, 'S', 'sand'],
      [3, 173, 17, 'S', 'sand'],
      [5, 614, 1, 'S', 'sand'],
      [4, 416, 10, 'S', 'sand'],
      [3, 221, 16, 'S', 'sand'],
      [4, 504, 2, 'R', 'sand'],
      [5, 612, 12, 'L', 'sand'],
      [4, 437, 8, 'S', 'sand'],
      [4, 478, 4, 'S', 'sand'],
      [3, 227, 14, 'S', 'ocean'],
      [4, 442, 6, 'R', 'sand'],
      [5, 568, 18, 'S', 'water', 'The par 5 where Tiger made the putt — water fronts the green'],
    ]),
  },
  {
    slug: 'pacific-dunes',
    name: 'Pacific Dunes',
    location: 'Bandon, Oregon',
    difficulty: 8,
    greens: 'Firm',
    wind: 20,
    blurb: 'Tom Doak’s coastal minimalist masterpiece, no two holes remotely alike.',
    holes: holes([
      [4, 370, 9, 'S', 'sand'],
      [4, 368, 11, 'R', 'sand'],
      [5, 499, 7, 'L', 'ocean'],
      [4, 463, 3, 'S', 'ocean'],
      [3, 199, 17, 'S', 'sand'],
      [4, 316, 13, 'R', 'sand'],
      [4, 464, 1, 'L', 'sand'],
      [4, 400, 5, 'S', 'sand'],
      [4, 406, 15, 'R', 'sand'],
      [3, 206, 14, 'S', 'ocean'],
      [3, 148, 18, 'S', 'ocean', 'The second of back-to-back par 3s, all carry along the surf'],
      [5, 529, 6, 'L', 'sand'],
      [4, 444, 2, 'S', 'ocean', 'The cliff’s-edge four — the ocean shoulders the whole fairway'],
      [3, 145, 16, 'S', 'sand'],
      [5, 539, 10, 'R', 'sand'],
      [4, 338, 12, 'S', 'sand'],
      [3, 208, 8, 'S', 'sand'],
      [5, 591, 4, 'L', 'sand'],
    ]),
  },
  {
    slug: 'pine-valley',
    name: 'Pine Valley',
    location: 'Pine Valley, New Jersey',
    difficulty: 10,
    greens: 'Firm',
    wind: 8,
    blurb: 'Often ranked the best in the world — sandy waste and forced carries everywhere.',
    holes: holes([
      [4, 421, 11, 'R', 'sand'],
      [4, 367, 15, 'S', 'sand'],
      [3, 198, 9, 'S', 'sand'],
      [4, 461, 3, 'R', 'sand'],
      [3, 232, 1, 'S', 'sand', 'The par 3 they call the hardest hole in the world'],
      [4, 388, 13, 'L', 'sand'],
      [5, 585, 5, 'S', 'sand', 'Hell’s Half Acre — a hundred yards of sand to cross on the second'],
      [4, 327, 17, 'S', 'sand'],
      [4, 432, 7, 'R', 'sand'],
      [3, 145, 14, 'S', 'sand', 'A tiny par 3 over a pit you don’t climb out of'],
      [4, 397, 12, 'L', 'sand'],
      [4, 337, 18, 'S', 'sand'],
      [4, 486, 2, 'R', 'sand'],
      [3, 184, 10, 'S', 'sand'],
      [5, 603, 6, 'L', 'sand'],
      [4, 436, 8, 'S', 'sand'],
      [4, 345, 16, 'S', 'sand'],
      [4, 483, 4, 'R', 'sand'],
    ]),
  },
  {
    slug: 'bandon-dunes',
    name: 'Bandon Dunes',
    location: 'Bandon, Oregon',
    difficulty: 8,
    greens: 'Firm',
    wind: 20,
    blurb: 'The course that started a pilgrimage — raw Oregon coast, firm and fast.',
    holes: holes([
      [4, 386, 13, 'S', 'sand'],
      [3, 220, 15, 'S', 'sand'],
      [5, 563, 3, 'R', 'sand'],
      [4, 443, 5, 'L', 'sand'],
      [4, 473, 1, 'S', 'ocean', 'Along the cliff’s edge — the Pacific down the entire right'],
      [3, 217, 17, 'S', 'sand'],
      [4, 411, 7, 'R', 'sand'],
      [4, 385, 11, 'L', 'sand'],
      [5, 605, 9, 'S', 'sand'],
      [4, 380, 8, 'R', 'sand'],
      [4, 469, 2, 'L', 'ocean'],
      [3, 238, 18, 'S', 'sand'],
      [5, 554, 6, 'R', 'sand'],
      [4, 390, 16, 'S', 'sand'],
      [3, 206, 14, 'S', 'ocean', 'A par 3 to a green teetering above the beach'],
      [4, 412, 10, 'L', 'sand'],
      [4, 405, 12, 'R', 'ocean'],
      [5, 558, 4, 'S', 'sand'],
    ]),
  },
  {
    slug: 'muirfield',
    name: 'Muirfield',
    location: 'East Lothian, Scotland',
    difficulty: 9,
    greens: 'Firm',
    wind: 20,
    blurb: 'The fairest of the Open rota — walls of bunkers and honest, brutal links wind.',
    holes: holes([
      [4, 446, 5, 'R', 'sand'],
      [4, 365, 11, 'L', 'sand'],
      [4, 377, 7, 'S', 'sand'],
      [3, 182, 9, 'S', 'sand'],
      [5, 510, 13, 'R', 'sand'],
      [4, 440, 1, 'L', 'sand'],
      [3, 147, 17, 'S', 'sand'],
      [4, 443, 3, 'R', 'sand'],
      [5, 505, 15, 'S', 'sand'],
      [4, 470, 4, 'L', 'sand'],
      [4, 354, 12, 'R', 'sand'],
      [4, 380, 10, 'S', 'sand'],
      [3, 156, 18, 'S', 'sand', 'A short par 3 ringed by walls of revetted sand'],
      [4, 449, 2, 'L', 'sand'],
      [4, 394, 8, 'R', 'sand'],
      [3, 186, 14, 'S', 'sand'],
      [5, 506, 16, 'L', 'sand'],
      [4, 418, 6, 'R', 'sand', 'Home to the grey clubhouse — a par 4 that decides Opens'],
    ]),
  },
  {
    slug: 'quail-hollow',
    name: 'Quail Hollow Club',
    location: 'Charlotte, North Carolina',
    difficulty: 8,
    greens: 'Fast',
    wind: 7,
    blurb: 'A modern tour stalwart ending in the water-lined Green Mile.',
    holes: holes([
      [4, 460, 7, 'L', 'sand'],
      [4, 452, 9, 'R', 'sand'],
      [4, 483, 3, 'S', 'sand'],
      [3, 184, 15, 'S', 'sand'],
      [4, 449, 11, 'R', 'sand'],
      [3, 249, 13, 'S', 'sand'],
      [5, 546, 5, 'L', 'sand'],
      [4, 346, 17, 'S', 'sand'],
      [4, 458, 1, 'R', 'sand'],
      [5, 592, 8, 'L', 'sand'],
      [4, 462, 6, 'S', 'sand'],
      [4, 456, 10, 'R', 'sand'],
      [3, 210, 14, 'S', 'sand'],
      [4, 344, 16, 'L', 'sand'],
      [5, 577, 12, 'R', 'sand'],
      [4, 505, 2, 'L', 'water', 'The Green Mile begins — water clings to the green'],
      [3, 223, 18, 'S', 'water', 'A long par 3 all carry over the water — the Mile bites'],
      [4, 494, 4, 'R', 'water', 'The Green Mile’s cruel last — creek all down the left'],
    ]),
  },
  {
    slug: 'shinnecock-hills',
    name: 'Shinnecock Hills',
    location: 'Southampton, New York',
    difficulty: 9,
    greens: 'Firm',
    wind: 18,
    blurb: 'Windblown fescue and firm greens on Long Island’s eastern end.',
    holes: holes([
      [4, 394, 17, 'S', 'sand'],
      [3, 252, 5, 'S', 'sand'],
      [4, 501, 1, 'R', 'sand'],
      [4, 476, 9, 'S', 'sand'],
      [5, 592, 11, 'L', 'sand'],
      [4, 495, 3, 'S', 'water'],
      [3, 187, 15, 'S', 'sand', 'The Redan seventh — feed it off the slope and let it chase'],
      [4, 440, 13, 'S', 'sand'],
      [4, 482, 7, 'R', 'sand'],
      [4, 415, 10, 'S', 'sand'],
      [3, 157, 16, 'S', 'sand'],
      [4, 469, 8, 'L', 'sand'],
      [4, 371, 18, 'S', 'none'],
      [4, 520, 2, 'R', 'sand'],
      [4, 409, 12, 'S', 'sand'],
      [5, 614, 6, 'R', 'sand'],
      [3, 176, 14, 'S', 'sand'],
      [4, 490, 4, 'S', 'sand', 'Uphill to the clubhouse — a windswept, brutal finish'],
    ]),
  },
  {
    slug: 'millbrook-valley',
    name: 'Millbrook Valley',
    location: 'Hollow Creek, Tennessee',
    difficulty: 7,
    greens: 'Fast',
    wind: 8,
    blurb: 'A mountain valley course where the creek is always listening.',
    holes: holes([
      [4, 469, 3, 'R', 'sand'],
      [3, 231, 7, 'S', 'sand'],
      [4, 353, 17, 'L', 'water'],
      [5, 546, 11, 'R', 'water', 'The creek crosses twice before the green'],
      [3, 187, 9, 'S', 'water'],
      [4, 445, 13, 'S', 'sand'],
      [4, 378, 15, 'R', 'water'],
      [5, 568, 5, 'L', 'sand'],
      [4, 433, 1, 'S', 'water', 'The valley’s meanest four — creek left, wall right'],
      [4, 392, 14, 'R', 'sand'],
      [5, 531, 12, 'L', 'water'],
      [3, 169, 16, 'S', 'water', 'An uphill carry to a nearly blind shelf', true],
      [4, 408, 6, 'S', 'sand'],
      [4, 297, 18, 'R', 'water', 'Drivable, but the pond guards the hero line'],
      [4, 481, 2, 'R', 'water'],
      [4, 417, 10, 'L', 'sand'],
      [3, 195, 8, 'S', 'water'],
      [5, 512, 4, 'S', 'water', 'Break-par-or-break-down finisher over the mill pond'],
    ]),
  },
  {
    slug: 'lacc-north',
    name: 'Los Angeles Country Club',
    location: 'Los Angeles, California',
    difficulty: 9,
    greens: 'Fast',
    wind: 6,
    blurb: 'A Gil Hanse restoration of barrancas and bold greens in the heart of L.A.',
    holes: holes([
      [5, 578, 17, 'R', 'sand'],
      [4, 503, 1, 'L', 'sand'],
      [4, 400, 9, 'S', 'sand'],
      [3, 234, 5, 'S', 'sand'],
      [4, 483, 3, 'R', 'sand'],
      [4, 335, 15, 'L', 'sand'],
      [4, 326, 7, 'S', 'sand'],
      [5, 555, 13, 'R', 'sand'],
      [3, 181, 11, 'S', 'sand'],
      [4, 409, 10, 'L', 'sand'],
      [3, 294, 16, 'S', 'sand', 'A par 3 that plays like a par 4 — nearly 300 yards of it'],
      [4, 388, 6, 'R', 'sand'],
      [4, 510, 2, 'L', 'sand'],
      [5, 633, 12, 'S', 'sand'],
      [3, 133, 18, 'S', 'sand', 'A wedge par 3 — but the barranca grants no mercy'],
      [4, 542, 8, 'R', 'sand'],
      [4, 528, 4, 'L', 'sand'],
      [4, 498, 14, 'S', 'sand'],
    ]),
  },
  {
    slug: 'cabot-links',
    name: 'Cabot Links',
    location: 'Inverness, Nova Scotia',
    difficulty: 7,
    greens: 'Firm',
    wind: 18,
    blurb: 'True links on the Nova Scotia shore, every hole in view of the Atlantic.',
    holes: holes([
      [5, 506, 15, 'S', 'sand'],
      [4, 410, 7, 'S', 'sand'],
      [4, 300, 17, 'S', 'ocean'],
      [3, 175, 9, 'S', 'sand'],
      [4, 455, 3, 'S', 'sand'],
      [4, 425, 5, 'R', 'ocean'],
      [3, 160, 13, 'S', 'sand'],
      [4, 470, 1, 'L', 'sand'],
      [4, 405, 11, 'S', 'sand'],
      [4, 415, 12, 'S', 'sand'],
      [5, 560, 10, 'S', 'sand'],
      [4, 430, 6, 'L', 'sand'],
      [4, 445, 4, 'S', 'sand'],
      [3, 200, 8, 'S', 'ocean'],
      [4, 380, 16, 'S', 'sand'],
      [3, 100, 18, 'S', 'ocean', 'A hundred-yard flick over the beach to the sea’s edge'],
      [4, 415, 14, 'S', 'ocean', 'Along the Atlantic shore for home'],
      [4, 470, 2, 'S', 'sand'],
    ]),
  },
  {
    slug: 'oakmont',
    name: 'Oakmont Country Club',
    location: 'Oakmont, Pennsylvania',
    difficulty: 10,
    greens: 'Fast',
    wind: 8,
    blurb: 'The hardest course in America — Church Pew bunkers and greens like polished glass.',
    holes: holes([
      [4, 488, 5, 'S', 'sand'],
      [4, 346, 13, 'S', 'sand'],
      [4, 462, 7, 'L', 'sand', 'The Church Pews — a ladder of sand you daren’t pray from'],
      [5, 611, 9, 'L', 'sand'],
      [4, 408, 11, 'R', 'sand'],
      [3, 200, 15, 'S', 'sand'],
      [4, 485, 3, 'S', 'sand'],
      [3, 289, 17, 'S', 'sand', 'A par 3 of nearly 300 yards — reach for the driver'],
      [4, 477, 1, 'S', 'sand'],
      [4, 461, 4, 'R', 'sand'],
      [4, 379, 14, 'S', 'sand'],
      [5, 632, 8, 'S', 'sand'],
      [3, 183, 16, 'S', 'sand'],
      [4, 379, 12, 'S', 'sand'],
      [4, 507, 2, 'L', 'sand'],
      [3, 231, 10, 'S', 'sand'],
      [4, 312, 18, 'S', 'sand'],
      [4, 502, 6, 'S', 'sand'],
    ]),
  },
  {
    slug: 'camargo',
    name: 'Camargo Club',
    location: 'Cincinnati, Ohio',
    difficulty: 7,
    greens: 'Firm',
    wind: 8,
    blurb: 'A Seth Raynor gem of template holes and bold, geometric greens.',
    holes: holes([
      [4, 390, 17, 'S', 'none'],
      [5, 529, 5, 'L', 'sand'],
      [4, 320, 13, 'R', 'sand'],
      [4, 454, 1, 'S', 'sand'],
      [3, 179, 15, 'S', 'sand'],
      [4, 368, 7, 'R', 'sand'],
      [4, 427, 3, 'S', 'none'],
      [3, 227, 11, 'S', 'sand', 'A textbook Redan — let the slope do the work'],
      [4, 432, 9, 'L', 'sand'],
      [4, 441, 2, 'S', 'sand'],
      [3, 140, 18, 'S', 'sand', 'The Short — a devilish little one-shotter'],
      [4, 415, 4, 'R', 'sand'],
      [4, 369, 16, 'L', 'sand'],
      [4, 390, 10, 'S', 'sand'],
      [3, 192, 14, 'S', 'sand'],
      [4, 420, 8, 'S', 'sand'],
      [5, 544, 12, 'R', 'sand'],
      [4, 422, 6, 'L', 'sand'],
    ]),
  },
  {
    slug: 'doral-blue-monster',
    name: 'Trump National Doral — Blue Monster',
    location: 'Miami, Florida',
    difficulty: 9,
    greens: 'Firm',
    wind: 12,
    blurb: 'Water down the right all day and a closing hole that has ended many rounds.',
    holes: holes([
      [5, 562, 9, 'S', 'water'],
      [4, 407, 11, 'R', 'sand'],
      [4, 434, 7, 'L', 'water'],
      [3, 234, 13, 'S', 'sand'],
      [4, 473, 3, 'R', 'water'],
      [4, 447, 5, 'L', 'sand'],
      [4, 430, 15, 'S', 'water'],
      [5, 599, 1, 'R', 'water'],
      [3, 178, 17, 'S', 'water'],
      [5, 564, 8, 'L', 'water'],
      [4, 440, 6, 'R', 'sand'],
      [5, 603, 10, 'S', 'water'],
      [3, 245, 12, 'S', 'sand'],
      [4, 483, 2, 'L', 'water'],
      [3, 175, 16, 'S', 'water'],
      [4, 280, 14, 'R', 'sand'],
      [4, 436, 4, 'L', 'water'],
      [4, 473, 18, 'L', 'water', 'The Blue Monster’s bite — water clings to the left for home'],
    ]),
  },
  {
    slug: 'erin-hills',
    name: 'Erin Hills',
    location: 'Erin, Wisconsin',
    difficulty: 8,
    greens: 'Firm',
    wind: 16,
    blurb: 'Big, rolling glacial terrain in Wisconsin with fescue that swallows loose shots.',
    holes: holes([
      [5, 608, 9, 'S', 'sand'],
      [4, 347, 15, 'S', 'none'],
      [4, 505, 3, 'L', 'sand'],
      [4, 450, 7, 'R', 'sand'],
      [4, 508, 5, 'S', 'sand'],
      [3, 217, 13, 'S', 'sand'],
      [5, 607, 11, 'L', 'sand'],
      [4, 430, 1, 'S', 'sand'],
      [3, 135, 17, 'S', 'sand', 'A little par 3 nestled in the glacial dunes'],
      [4, 410, 8, 'R', 'sand'],
      [4, 391, 14, 'S', 'none'],
      [4, 460, 4, 'L', 'sand'],
      [3, 195, 16, 'S', 'sand'],
      [5, 594, 10, 'R', 'sand'],
      [4, 372, 12, 'S', 'none'],
      [3, 196, 18, 'S', 'sand'],
      [4, 451, 6, 'S', 'sand'],
      [5, 637, 2, 'S', 'sand', 'A 630-yard brute to finish — the fescue swallows the timid'],
    ]),
  },
  {
    slug: 'winged-foot-west',
    name: 'Winged Foot — West',
    location: 'Mamaroneck, New York',
    difficulty: 9,
    greens: 'Fast',
    wind: 8,
    blurb: 'Tillinghast’s brute — deep bunkers and greens that have broken major champions.',
    holes: holes([
      [4, 450, 9, 'S', 'sand'],
      [4, 453, 7, 'R', 'sand'],
      [3, 243, 15, 'S', 'sand'],
      [4, 469, 5, 'L', 'sand'],
      [5, 515, 13, 'R', 'sand'],
      [4, 321, 17, 'S', 'sand'],
      [3, 162, 11, 'S', 'sand'],
      [4, 475, 3, 'L', 'sand'],
      [4, 514, 1, 'R', 'sand'],
      [3, 188, 16, 'S', 'sand', 'The par 3 Hogan likened to a 3-iron into a bedroom'],
      [4, 397, 12, 'S', 'sand'],
      [5, 640, 8, 'R', 'sand'],
      [3, 214, 14, 'S', 'sand'],
      [4, 458, 6, 'L', 'sand'],
      [4, 416, 10, 'S', 'sand'],
      [4, 478, 2, 'R', 'sand'],
      [4, 504, 4, 'L', 'sand'],
      [4, 469, 18, 'S', 'sand', 'Tillinghast’s fearsome finish — par is a triumph'],
    ]),
  },
  {
    slug: 'national-golf-links',
    name: 'National Golf Links of America',
    location: 'Southampton, New York',
    difficulty: 8,
    greens: 'Firm',
    wind: 14,
    blurb: 'The template course that shaped American golf, wild greens beside the bay.',
    holes: holes([
      [4, 330, 11, 'R', 'sand'],
      [4, 330, 15, 'L', 'sand'],
      [4, 426, 1, 'S', 'sand', 'The Alps — a blind carry over the dune to a hidden green'],
      [3, 195, 13, 'S', 'sand', 'The Redan — the template that launched a thousand copies'],
      [4, 478, 3, 'R', 'sand'],
      [3, 141, 17, 'S', 'sand'],
      [5, 478, 9, 'L', 'sand'],
      [4, 400, 5, 'S', 'sand'],
      [5, 540, 7, 'R', 'sand'],
      [4, 450, 4, 'L', 'sand'],
      [4, 432, 10, 'S', 'water'],
      [4, 459, 2, 'R', 'sand'],
      [3, 174, 18, 'S', 'sand'],
      [4, 393, 12, 'L', 'sand'],
      [4, 417, 6, 'S', 'sand'],
      [4, 415, 14, 'R', 'sand'],
      [4, 375, 16, 'L', 'sand'],
      [5, 502, 8, 'S', 'water'],
    ]),
  },
  {
    slug: 'the-country-club',
    name: 'The Country Club',
    location: 'Brookline, Massachusetts',
    difficulty: 9,
    greens: 'Fast',
    wind: 8,
    blurb: 'Brookline’s rocky, tree-lined stage for some of golf’s greatest upsets.',
    holes: holes([
      [4, 495, 7, 'R', 'sand'],
      [3, 220, 11, 'S', 'sand'],
      [4, 504, 1, 'L', 'sand'],
      [4, 323, 9, 'R', 'sand'],
      [4, 497, 3, 'S', 'sand'],
      [4, 310, 17, 'L', 'sand'],
      [3, 197, 15, 'S', 'sand'],
      [4, 380, 13, 'R', 'sand'],
      [4, 426, 5, 'L', 'sand'],
      [4, 334, 16, 'S', 'sand'],
      [5, 513, 12, 'R', 'sand'],
      [3, 131, 18, 'S', 'sand'],
      [4, 478, 2, 'L', 'sand'],
      [5, 567, 8, 'R', 'sand'],
      [4, 430, 6, 'S', 'sand'],
      [3, 205, 14, 'S', 'sand'],
      [4, 375, 10, 'L', 'sand', 'The 17th — where Brookline’s amateurs became legends'],
      [4, 455, 4, 'R', 'sand'],
    ]),
  },
  {
    slug: 'whispering-pines',
    name: 'Whispering Pines',
    location: 'Trinity, Texas',
    difficulty: 8,
    greens: 'Fast',
    wind: 6,
    blurb: 'A pristine, secluded Texas pine forest with water in play at every turn.',
    holes: holes([
      [4, 388, 17, 'L', 'none'],
      [5, 560, 5, 'R', 'sand'],
      [3, 208, 15, 'S', 'sand'],
      [4, 488, 3, 'S', 'sand'],
      [5, 574, 7, 'S', 'water'],
      [4, 391, 9, 'R', 'sand'],
      [4, 472, 1, 'L', 'sand'],
      [3, 194, 13, 'S', 'sand'],
      [4, 429, 11, 'R', 'none'],
      [4, 426, 14, 'L', 'sand'],
      [4, 411, 6, 'S', 'sand'],
      [5, 535, 18, 'S', 'sand'],
      [4, 468, 4, 'R', 'water'],
      [4, 370, 16, 'S', 'sand'],
      [3, 178, 10, 'S', 'water'],
      [3, 252, 12, 'S', 'water', 'A 250-yard iron over the water — nowhere to bail'],
      [5, 629, 8, 'L', 'water'],
      [4, 495, 2, 'R', 'water'],
    ]),
  },
  {
    slug: 'royal-birkdale',
    name: 'Royal Birkdale',
    location: 'Southport, England',
    difficulty: 9,
    greens: 'Firm',
    wind: 20,
    blurb: 'Flat-bottomed fairways winding through towering dunes on the English coast.',
    holes: holes([
      [4, 447, 5, 'R', 'sand'],
      [4, 419, 11, 'S', 'sand'],
      [4, 450, 7, 'L', 'sand'],
      [3, 219, 13, 'S', 'sand'],
      [4, 321, 17, 'S', 'sand'],
      [4, 514, 1, 'R', 'sand'],
      [3, 151, 15, 'S', 'sand'],
      [4, 459, 3, 'L', 'sand'],
      [4, 411, 9, 'R', 'sand'],
      [4, 408, 8, 'S', 'sand'],
      [4, 436, 6, 'L', 'sand'],
      [3, 184, 14, 'S', 'sand', 'A celebrated par 3 framed tight by towering dunes'],
      [4, 499, 2, 'R', 'sand'],
      [3, 201, 16, 'S', 'sand'],
      [5, 544, 10, 'L', 'sand'],
      [4, 439, 4, 'R', 'sand'],
      [5, 572, 12, 'S', 'sand'],
      [4, 508, 18, 'L', 'sand', 'The long march home through the dunes to the clubhouse'],
    ]),
  },
  {
    slug: 'merion-east',
    name: 'Merion Golf Club — East',
    location: 'Ardmore, Pennsylvania',
    difficulty: 8,
    greens: 'Fast',
    wind: 8,
    blurb: 'Small, subtle, and deadly — wicker baskets for flags and no room for error.',
    holes: holes([
      [4, 350, 13, 'R', 'sand'],
      [5, 556, 7, 'S', 'sand'],
      [3, 256, 9, 'S', 'sand'],
      [5, 628, 1, 'R', 'sand'],
      [4, 504, 3, 'L', 'sand'],
      [4, 487, 5, 'R', 'sand'],
      [4, 360, 15, 'S', 'sand'],
      [4, 359, 11, 'L', 'sand'],
      [3, 236, 17, 'S', 'sand'],
      [4, 303, 16, 'S', 'sand', 'The Quarry — all carry to a green cut from the rock'],
      [4, 367, 14, 'R', 'water', 'Where Bobby Jones sealed the Grand Slam, the brook waiting'],
      [4, 403, 10, 'S', 'sand'],
      [3, 115, 18, 'S', 'sand'],
      [4, 464, 6, 'S', 'sand'],
      [4, 411, 8, 'S', 'sand'],
      [4, 430, 4, 'R', 'sand'],
      [3, 246, 12, 'S', 'sand'],
      [4, 521, 2, 'S', 'sand', 'Hogan’s 1-iron — a long four back over the quarry'],
    ]),
  },
  {
    slug: 'kiawah-ocean',
    name: 'Kiawah Island — Ocean Course',
    location: 'Kiawah Island, South Carolina',
    difficulty: 10,
    greens: 'Firm',
    wind: 18,
    blurb: 'The Ocean Course — wind off the Atlantic and nowhere to hide down the stretch.',
    holes: holes([
      [4, 395, 11, 'S', 'sand'],
      [5, 543, 9, 'R', 'ocean'],
      [4, 390, 13, 'S', 'sand'],
      [4, 453, 5, 'L', 'water'],
      [3, 207, 15, 'S', 'ocean'],
      [4, 455, 3, 'R', 'sand'],
      [5, 579, 7, 'L', 'ocean'],
      [3, 197, 17, 'S', 'water', 'A par 3 over the water — where the War by the Shore was won'],
      [4, 464, 1, 'R', 'sand'],
      [4, 439, 8, 'S', 'sand'],
      [5, 593, 10, 'L', 'water'],
      [4, 466, 4, 'R', 'sand'],
      [4, 404, 12, 'S', 'ocean'],
      [3, 194, 16, 'S', 'ocean'],
      [4, 470, 2, 'L', 'sand'],
      [5, 579, 14, 'R', 'ocean'],
      [3, 221, 6, 'S', 'ocean'],
      [4, 439, 18, 'S', 'ocean', 'Into the teeth of the wind — the Ocean Course’s cruel last'],
    ]),
  },
  {
    slug: 'arcadia-bluffs',
    name: 'Arcadia Bluffs',
    location: 'Arcadia, Michigan',
    difficulty: 8,
    greens: 'Firm',
    wind: 18,
    blurb: 'Windswept dunes high above Lake Michigan, links golf transplanted to the Midwest.',
    holes: holes([
      [5, 499, 15, 'R', 'sand'],
      [3, 180, 17, 'S', 'sand'],
      [5, 520, 7, 'L', 'sand'],
      [4, 411, 13, 'S', 'sand'],
      [5, 570, 3, 'R', 'sand'],
      [3, 186, 9, 'S', 'sand'],
      [4, 430, 1, 'L', 'sand'],
      [4, 383, 5, 'S', 'sand'],
      [3, 194, 11, 'S', 'ocean', 'A par 3 poised on the bluff high above the lake'],
      [4, 422, 2, 'R', 'sand'],
      [5, 597, 12, 'L', 'sand'],
      [4, 422, 10, 'S', 'sand'],
      [3, 181, 8, 'S', 'sand'],
      [4, 337, 14, 'R', 'sand'],
      [5, 465, 18, 'S', 'sand'],
      [4, 457, 4, 'L', 'ocean', 'High on the bluff — Lake Michigan fills the whole horizon'],
      [3, 175, 16, 'S', 'sand'],
      [4, 429, 6, 'S', 'sand'],
    ]),
  },
  {
    slug: 'prairie-dunes',
    name: 'Prairie Dunes Country Club',
    location: 'Hutchinson, Kansas',
    difficulty: 9,
    greens: 'Firm',
    wind: 17,
    blurb: 'Sandhills links in Kansas — yucca, cottonwoods, and relentless plains wind.',
    holes: holes([
      [4, 452, 7, 'S', 'sand'],
      [3, 164, 15, 'S', 'sand', 'A gem of a par 3 tucked among the yucca and dunes'],
      [4, 355, 13, 'R', 'sand'],
      [3, 171, 17, 'S', 'sand'],
      [4, 477, 3, 'R', 'sand'],
      [4, 387, 11, 'L', 'sand'],
      [5, 512, 9, 'R', 'sand'],
      [4, 468, 1, 'L', 'sand'],
      [4, 452, 5, 'L', 'sand'],
      [3, 190, 16, 'S', 'sand'],
      [4, 535, 2, 'L', 'water'],
      [4, 395, 8, 'R', 'sand'],
      [4, 445, 10, 'L', 'sand'],
      [4, 405, 12, 'S', 'sand'],
      [3, 200, 18, 'S', 'sand'],
      [4, 426, 4, 'R', 'sand'],
      [5, 523, 6, 'L', 'sand'],
      [4, 390, 14, 'R', 'sand'],
    ]),
  },
  {
    slug: 'pinehurst-no2',
    name: 'Pinehurst No. 2',
    location: 'Pinehurst, North Carolina',
    difficulty: 8,
    greens: 'Firm',
    wind: 8,
    blurb: 'Donald Ross’s turtleback greens repel anything less than perfect.',
    holes: holes([
      [4, 404, 7, 'R', 'sand'],
      [4, 507, 3, 'S', 'sand'],
      [4, 387, 11, 'R', 'sand'],
      [5, 529, 13, 'L', 'sand'],
      [4, 476, 5, 'R', 'sand', 'A Ross classic — the turtleback shrugs off all but the best'],
      [3, 223, 17, 'S', 'sand'],
      [4, 407, 1, 'L', 'sand'],
      [4, 488, 9, 'R', 'sand'],
      [3, 191, 15, 'S', 'sand'],
      [5, 617, 12, 'L', 'sand'],
      [4, 483, 6, 'R', 'sand'],
      [4, 484, 2, 'S', 'sand'],
      [4, 380, 8, 'L', 'sand'],
      [4, 473, 4, 'R', 'sand'],
      [3, 202, 18, 'S', 'sand'],
      [4, 489, 10, 'R', 'sand'],
      [3, 205, 16, 'S', 'sand'],
      [4, 451, 14, 'L', 'sand', 'Payne Stewart’s stage — par into the crowned green to win'],
    ]),
  },
  {
    slug: 'riviera',
    name: 'The Riviera Country Club',
    location: 'Pacific Palisades, California',
    difficulty: 9,
    greens: 'Fast',
    wind: 10,
    blurb: 'Hogan’s Alley — kikuyu rough, a bunker in the middle of a green, timeless design.',
    holes: holes([
      [5, 503, 17, 'S', 'sand'],
      [4, 471, 1, 'R', 'sand'],
      [4, 434, 7, 'L', 'sand'],
      [3, 273, 9, 'S', 'sand'],
      [4, 434, 5, 'L', 'sand'],
      [3, 199, 15, 'S', 'sand', 'The par 3 with a bunker smack in the middle of the green'],
      [4, 408, 11, 'R', 'sand'],
      [4, 433, 13, 'S', 'sand'],
      [4, 458, 3, 'L', 'sand'],
      [4, 315, 16, 'R', 'sand', 'The little tenth — the cleverest short par 4 in golf'],
      [5, 583, 10, 'L', 'sand'],
      [4, 479, 8, 'R', 'sand'],
      [4, 459, 6, 'L', 'sand'],
      [3, 192, 18, 'S', 'sand'],
      [4, 487, 2, 'R', 'sand'],
      [3, 166, 14, 'S', 'sand'],
      [5, 590, 12, 'L', 'sand'],
      [4, 499, 4, 'R', 'sand', 'Uphill to the amphitheater — Hogan’s Alley signs off'],
    ]),
  },
  {
    slug: 'cypress-hollow',
    name: 'Cypress Hollow',
    location: 'Ponte Vedra, Florida',
    difficulty: 8,
    greens: 'Fast',
    wind: 9,
    blurb: 'Water on fourteen holes. Target golf, no bailouts.',
    holes: holes([
      [4, 401, 7, 'S', 'water'],
      [5, 533, 11, 'R', 'water'],
      [3, 172, 15, 'S', 'water'],
      [4, 448, 1, 'L', 'water', 'Water left, water long — the pros lay back here'],
      [4, 379, 13, 'R', 'sand'],
      [4, 421, 5, 'S', 'water'],
      [3, 194, 9, 'S', 'sand'],
      [5, 571, 3, 'L', 'water', 'Reachable, but the lake hugs the last ninety yards'],
      [4, 356, 17, 'S', 'none'],
      [4, 417, 6, 'R', 'water'],
      [5, 524, 12, 'S', 'sand'],
      [4, 438, 2, 'L', 'water'],
      [3, 161, 14, 'S', 'water', 'All carry over the lily pond', true],
      [4, 391, 10, 'R', 'sand'],
      [4, 428, 4, 'S', 'water'],
      [5, 507, 16, 'R', 'water', 'A gambler’s five — water rings the peninsula green'],
      [3, 132, 18, 'S', 'water', 'The Island — no drop zone mercy today', true],
      [4, 411, 8, 'L', 'water', 'Water down the left the whole way home'],
    ]),
  },
  {
    slug: 'royal-melbourne',
    name: 'Royal Melbourne',
    location: 'Victoria, Australia',
    difficulty: 8,
    greens: 'Fast',
    wind: 16,
    blurb: 'Alister MacKenzie’s Sandbelt masterpiece, fast fairways and cunning bunkers.',
    holes: holes([
      [4, 373, 15, 'R', 'sand'],
      [5, 533, 9, 'L', 'sand'],
      [3, 176, 11, 'S', 'sand'],
      [4, 439, 7, 'R', 'sand'],
      [3, 148, 13, 'S', 'sand'],
      [4, 312, 17, 'L', 'sand', 'A drivable short four — MacKenzie’s bunkers dare you to try'],
      [4, 455, 3, 'S', 'sand'],
      [4, 476, 1, 'R', 'sand'],
      [4, 440, 5, 'L', 'sand'],
      [4, 433, 12, 'S', 'sand'],
      [4, 332, 18, 'R', 'sand'],
      [4, 440, 8, 'L', 'sand'],
      [4, 383, 16, 'S', 'sand'],
      [3, 189, 14, 'S', 'sand'],
      [5, 569, 6, 'R', 'sand'],
      [4, 474, 2, 'L', 'sand'],
      [4, 436, 10, 'S', 'sand'],
      [4, 458, 4, 'R', 'sand'],
    ]),
  },
  {
    slug: 'bethpage-black',
    name: 'Bethpage Black',
    location: 'Farmingdale, New York',
    difficulty: 9,
    greens: 'Medium',
    wind: 12,
    blurb: 'The people’s major venue, long and punishing, with a warning sign at the first tee.',
    holes: holes([
      [4, 430, 5, 'R', 'sand', 'The Warning-sign tee — Bethpage never eases you in'],
      [4, 389, 7, 'L', 'sand'],
      [3, 230, 17, 'S', 'sand'],
      [5, 517, 11, 'L', 'sand', 'A par 5 across a diagonal wall of sand — Tillinghast at his boldest'],
      [4, 478, 1, 'L', 'sand'],
      [4, 408, 9, 'R', 'sand'],
      [4, 489, 3, 'S', 'sand'],
      [3, 210, 15, 'S', 'sand'],
      [4, 460, 13, 'L', 'sand'],
      [4, 502, 4, 'S', 'sand'],
      [4, 435, 6, 'R', 'sand'],
      [4, 499, 8, 'L', 'sand'],
      [5, 608, 12, 'R', 'sand'],
      [3, 161, 16, 'S', 'sand'],
      [4, 478, 2, 'L', 'sand'],
      [4, 490, 10, 'R', 'sand'],
      [3, 207, 18, 'S', 'sand'],
      [4, 411, 14, 'S', 'sand'],
    ]),
  },
  {
    slug: 'royal-dornoch',
    name: 'Royal Dornoch — Championship',
    location: 'Dornoch, Scotland',
    difficulty: 8,
    greens: 'Firm',
    wind: 16,
    blurb: 'Remote, ancient, and revered — raised greens far up the Highland shore.',
    holes: holes([
      [4, 331, 12, 'S', 'none'],
      [3, 184, 6, 'S', 'none'],
      [4, 413, 14, 'R', 'sand'],
      [4, 422, 4, 'S', 'sand'],
      [4, 353, 18, 'L', 'sand'],
      [3, 161, 8, 'S', 'sand'],
      [4, 485, 2, 'S', 'sand'],
      [4, 482, 16, 'L', 'sand'],
      [5, 529, 10, 'S', 'none'],
      [3, 174, 11, 'S', 'sand'],
      [4, 446, 3, 'S', 'sand'],
      [5, 560, 7, 'S', 'none'],
      [3, 180, 15, 'S', 'sand'],
      [4, 445, 1, 'R', 'none', 'Foxy — a double dogleg with never a bunker in sight'],
      [4, 360, 17, 'S', 'none'],
      [4, 401, 5, 'S', 'sand'],
      [4, 417, 13, 'L', 'none'],
      [4, 456, 9, 'S', 'none'],
    ]),
  },
  {
    slug: 'royal-troon',
    name: 'Royal Troon — Old Course',
    location: 'Troon, Scotland',
    difficulty: 9,
    greens: 'Firm',
    wind: 17,
    blurb: 'Home of the Postage Stamp — the tiniest, scariest par 3 in the Open rota.',
    holes: holes([
      [4, 370, 15, 'S', 'none'],
      [4, 391, 7, 'R', 'sand'],
      [4, 379, 11, 'L', 'sand'],
      [5, 555, 3, 'S', 'sand'],
      [3, 210, 13, 'S', 'sand'],
      [5, 601, 1, 'L', 'sand', 'The longest hole in Open golf — 600 yards into the breeze'],
      [4, 405, 9, 'R', 'sand'],
      [3, 123, 17, 'S', 'sand', 'The Postage Stamp — 123 yards to a green you could cover with a hankie'],
      [4, 422, 5, 'S', 'sand'],
      [4, 452, 10, 'R', 'sand'],
      [4, 483, 2, 'L', 'sand', 'The Railway — gorse to the right, sleepers left, no room at all'],
      [4, 429, 6, 'S', 'sand'],
      [4, 473, 12, 'R', 'sand'],
      [3, 178, 16, 'S', 'sand'],
      [4, 502, 4, 'L', 'sand'],
      [5, 553, 8, 'S', 'sand'],
      [3, 218, 14, 'S', 'sand'],
      [4, 464, 18, 'S', 'sand'],
    ]),
  },
  {
    slug: 'paynes-valley',
    name: 'Payne’s Valley',
    location: 'Hollister, Missouri',
    difficulty: 7,
    greens: 'Fast',
    wind: 8,
    blurb: 'Tiger’s first public design, carved into the Ozarks with room to swing.',
    holes: holes([
      [4, 483, 3, 'L', 'sand'],
      [3, 267, 7, 'S', 'sand'],
      [4, 334, 17, 'R', 'water'],
      [5, 544, 11, 'R', 'sand'],
      [3, 188, 9, 'S', 'water', 'A par 3 over the water, framed by Ozark bluffs'],
      [4, 444, 13, 'L', 'sand'],
      [4, 368, 15, 'S', 'sand'],
      [5, 567, 5, 'R', 'sand'],
      [4, 429, 1, 'L', 'water'],
      [3, 183, 16, 'S', 'sand'],
      [4, 429, 12, 'R', 'water'],
      [4, 341, 18, 'L', 'sand'],
      [5, 653, 2, 'S', 'sand'],
      [4, 421, 10, 'R', 'sand'],
      [4, 456, 4, 'L', 'water'],
      [3, 224, 14, 'S', 'sand'],
      [4, 487, 8, 'R', 'water'],
      [5, 552, 6, 'L', 'water'],
    ]),
  },
  {
    slug: 'aronimink',
    name: 'Aronimink Golf Club',
    location: 'Newtown Square, Pennsylvania',
    difficulty: 8,
    greens: 'Fast',
    wind: 6,
    blurb: 'A muscular Donald Ross parkland test where par is a genuine achievement.',
    holes: holes([
      [4, 448, 7, 'R', 'sand'],
      [4, 405, 13, 'S', 'sand'],
      [3, 191, 15, 'S', 'sand'],
      [4, 480, 1, 'L', 'sand'],
      [4, 435, 9, 'R', 'sand'],
      [3, 232, 11, 'S', 'sand'],
      [4, 446, 5, 'L', 'sand'],
      [3, 172, 17, 'S', 'sand'],
      [5, 578, 3, 'R', 'sand'],
      [4, 405, 12, 'S', 'sand'],
      [4, 400, 14, 'L', 'sand'],
      [4, 460, 2, 'R', 'sand'],
      [4, 452, 6, 'S', 'sand'],
      [3, 200, 16, 'S', 'sand'],
      [4, 421, 10, 'L', 'sand'],
      [5, 542, 8, 'R', 'sand'],
      [4, 440, 4, 'S', 'sand'],
      [4, 460, 18, 'L', 'sand', 'A muscular Ross finish — uphill all the way home'],
    ]),
  },
  {
    slug: 'muirfield-village',
    name: 'Muirfield Village Golf Club',
    location: 'Dublin, Ohio',
    difficulty: 10,
    greens: 'Fast',
    wind: 9,
    blurb: 'Jack’s masterpiece, immaculate and demanding, every green a puzzle.',
    holes: holes([
      [4, 490, 13, 'S', 'sand'],
      [4, 459, 3, 'L', 'water'],
      [4, 392, 9, 'R', 'water'],
      [3, 210, 17, 'S', 'sand'],
      [5, 547, 1, 'L', 'water'],
      [4, 455, 7, 'S', 'water'],
      [5, 582, 5, 'S', 'sand'],
      [3, 200, 15, 'S', 'sand'],
      [4, 417, 11, 'R', 'water'],
      [4, 472, 4, 'L', 'sand'],
      [5, 588, 10, 'S', 'water'],
      [3, 180, 16, 'S', 'water'],
      [4, 455, 14, 'L', 'sand'],
      [4, 360, 8, 'R', 'water', 'A short four guarded by the creek — Jack’s temptation'],
      [5, 561, 2, 'L', 'water'],
      [3, 218, 18, 'S', 'water'],
      [4, 503, 12, 'R', 'water'],
      [4, 484, 6, 'R', 'water', 'Jack’s uphill finish — the Memorial is won and lost here'],
    ]),
  },
  {
    slug: 'old-wick-links',
    name: 'Old Wick Links',
    location: 'East Lothian, Scotland',
    difficulty: 6,
    greens: 'Fast',
    wind: 18,
    blurb: 'Ancient linksland. Pot bunkers with names, wind with opinions.',
    holes: holes([
      [4, 358, 12, 'S', 'sand'],
      [4, 411, 4, 'S', 'sand'],
      [3, 164, 16, 'S', 'sand', 'Eleven bunkers ring a green the size of a kitchen'],
      [5, 512, 10, 'S', 'sand'],
      [4, 427, 2, 'R', 'sand', 'The Coffins — carry them or play backwards'],
      [4, 382, 8, 'S', 'none'],
      [3, 188, 14, 'S', 'sand'],
      [4, 443, 6, 'S', 'sand'],
      [5, 578, 18, 'S', 'sand', 'Downwind home — the easiest five on the coast'],
      [4, 391, 9, 'S', 'sand'],
      [3, 143, 17, 'S', 'sand'],
      [4, 462, 1, 'R', 'sand', 'The hardest two-shotter in the shire'],
      [4, 373, 13, 'L', 'none'],
      [5, 529, 11, 'S', 'sand'],
      [4, 404, 5, 'S', 'sand'],
      [3, 209, 7, 'S', 'sand', 'A long iron into an amphitheater of sod walls'],
      [4, 366, 15, 'S', 'none'],
      [5, 543, 3, 'R', 'sand', 'The burn crosses twice on the way home'],
    ]),
  },
  {
    slug: 'chambers-bay',
    name: 'Chambers Bay',
    location: 'University Place, Washington',
    difficulty: 9,
    greens: 'Firm',
    wind: 16,
    blurb: 'A walking-only quarry links with fescue, humps, and one lonely tree.',
    holes: holes([
      [4, 595, 3, 'R', 'sand'],
      [4, 415, 9, 'L', 'sand'],
      [3, 192, 15, 'S', 'sand'],
      [5, 529, 13, 'R', 'sand'],
      [4, 480, 5, 'S', 'sand'],
      [4, 508, 7, 'L', 'sand'],
      [4, 496, 1, 'R', 'sand'],
      [5, 604, 17, 'S', 'sand'],
      [3, 219, 11, 'S', 'sand'],
      [4, 468, 4, 'L', 'sand'],
      [4, 528, 8, 'R', 'sand'],
      [4, 295, 18, 'S', 'sand'],
      [5, 527, 14, 'L', 'sand'],
      [4, 542, 2, 'R', 'sand'],
      [3, 239, 16, 'S', 'sand', 'The lone fir stands sentinel over the green'],
      [4, 420, 10, 'S', 'sand'],
      [3, 212, 6, 'S', 'sand'],
      [5, 598, 12, 'L', 'sand', 'A rumpled par 5 home — where the U.S. Open came down to the wire'],
    ]),
  },
]

/**
 * Par-3 short courses — unlimited play only, never part of the daily rotation
 * (the rotation is COURSES order; adding here can't shift anyone's daily).
 * Hole yardages and handicap ranks come straight from each club's published
 * scorecard (longest tees; where a card lists two yardages the longer plays).
 * Real courses keep real hole counts: 9, 10, and 18-hole rounds all work.
 *
 * Stroke indexes are the scorecard's handicap RANKS spread over 1-18 (rank r
 * of n holes → si ≈ 1 + (r-1)·17/(n-1)), because the pressure model reads
 * strokeIndex on a 1-18 scale — a 9-hole card's raw 1-9 ranks would make the
 * whole course read as one long gauntlet.
 */
export const PAR3_COURSES: CourseSpec[] = [
  {
    slug: 'cobblestone-creek',
    name: 'Cobblestone Creek',
    location: 'Norman, Oklahoma',
    difficulty: 4,
    greens: 'Medium',
    wind: 12,
    blurb: 'Nine one-shotters on the Oklahoma plains — two of them 225-yard brutes.',
    par3Course: true,
    holes: holes([
      // black tees, 1479 yards — scorecard ranks 7,8,4,1,6,5,2,9,3;
      // hazards follow the OSM-imported geometry (see geometry.ts)
      [3, 176, 13, 'S', 'sand'],
      [3, 150, 15, 'S', 'sand'],
      [3, 168, 7, 'S', 'sand'],
      [3, 225, 1, 'S', 'water', 'All of 225 yards, creek crossing mid-flight — the longest short hole in town'],
      [3, 108, 11, 'S', 'none'],
      [3, 150, 9, 'S', 'water'],
      [3, 185, 3, 'S', 'sand'],
      [3, 92, 17, 'S', 'sand'],
      [3, 225, 5, 'S', 'sand'],
    ]),
  },
  {
    slug: 'the-swing',
    name: 'PGA Frisco — The Swing',
    location: 'Frisco, Texas',
    difficulty: 2,
    greens: 'Fast',
    wind: 9,
    blurb: 'Ten wedges under the Frisco lights — bunkers everywhere, excuses nowhere.',
    par3Course: true,
    holes: holes([
      // 770 yards over ten holes — ranks derived from yardage (card lists none)
      [3, 75, 10, 'S', 'sand'],
      [3, 77, 5, 'S', 'sand'],
      [3, 88, 3, 'S', 'sand'],
      [3, 70, 14, 'S', 'sand'],
      [3, 103, 1, 'S', 'sand', 'The long one — a full swing at last, sand all around'],
      [3, 77, 7, 'S', 'none'],
      [3, 69, 16, 'S', 'sand'],
      [3, 71, 12, 'S', 'sand'],
      [3, 64, 18, 'S', 'none'],
      [3, 76, 9, 'S', 'sand'],
    ]),
  },
  {
    slug: 'palm-beach-par-3',
    name: 'Palm Beach Par 3',
    location: 'Palm Beach, Florida',
    difficulty: 4,
    greens: 'Medium',
    wind: 14,
    blurb: 'Eighteen postcard par 3s squeezed between the Atlantic and the Intracoastal.',
    par3Course: true,
    holes: holes([
      // black tees, 2572 yards — dual-yardage holes play the longer number;
      // hazards follow the OSM-imported geometry: the Atlantic rides 4-8,
      // lakes flank the openers and the run home
      [3, 167, 7, 'S', 'water'],
      [3, 126, 13, 'S', 'water'],
      [3, 196, 3, 'S', 'water'],
      [3, 211, 1, 'S', 'ocean', 'The card says 211 — carry the water with the Atlantic hard on your left'],
      [3, 176, 5, 'S', 'ocean'],
      [3, 128, 11, 'S', 'ocean'],
      [3, 108, 15, 'S', 'ocean', 'A flip wedge with the Atlantic breathing down your right'],
      [3, 133, 9, 'S', 'ocean'],
      [3, 81, 17, 'S', 'sand'],
      [3, 112, 18, 'S', 'sand'],
      [3, 108, 16, 'S', 'sand'],
      [3, 126, 12, 'S', 'sand'],
      [3, 171, 6, 'S', 'sand'],
      [3, 129, 10, 'S', 'sand'],
      [3, 156, 4, 'S', 'water'],
      [3, 117, 14, 'S', 'water'],
      [3, 148, 8, 'S', 'water'],
      [3, 179, 2, 'S', 'water'],
    ]),
  },
]

/** Every playable course: the daily-rotation library plus the par-3 courses. */
export const ALL_COURSES: CourseSpec[] = [...COURSES, ...PAR3_COURSES]

// Reconcile hole yardage with imported OSM geometry: where a hole has real
// geography, its measured length is the single source of truth, so the tuple's
// yardage (a hand estimate) is snapped to it. Keeps the header, scorecard,
// course total, and map all agreeing. Automatic — freezing a hole into
// geometry.ts is the whole process; nothing here needs hand-editing.
// (Par-3 course geometry is authored the other way around — zones normalized
// to the published scorecard yardage — so this snap is a no-op there.)
for (const course of ALL_COURSES) {
  for (const hole of course.holes) {
    const geo = OSM_GEOMETRY[`${course.slug}:${hole.number}`]
    if (geo) hole.yards = geo.length
  }
}

export function courseBySlug(slug: string): CourseSpec | undefined {
  return ALL_COURSES.find((c) => c.slug === slug)
}

/**
 * A course's display-only Play Rating (1–10): how hard the course actually
 * plays, measured by simulation (see scripts/gen-play-ratings.ts). This is
 * deliberately separate from the internal `difficulty` field, which feeds the
 * odds engine and carries a hidden daily jitter. Falls back to `difficulty`
 * for any course missing from the generated table (e.g. a brand-new course
 * added before `pnpm gen:ratings` is re-run).
 */
export function playRatingFor(slug: string): number {
  return PLAY_RATINGS[slug] ?? courseBySlug(slug)?.difficulty ?? 5
}
