import type { CourseSpec, HoleSpec, Dogleg, HazardStyle } from './types'

type Row = [3 | 4 | 5, number, number, Dogleg, HazardStyle, string?]

function holes(rows: Row[]): HoleSpec[] {
  return rows.map(([par, yards, strokeIndex, dogleg, hazard, signature], i) => ({
    number: i + 1,
    par,
    yards,
    strokeIndex,
    dogleg,
    hazard,
    signature,
  }))
}

export const COURSES: CourseSpec[] = [
  {
    slug: 'gullwing-point',
    name: 'Gullwing Point',
    location: 'Mendocino, California',
    difficulty: 7,
    greens: 'Firm',
    wind: 14,
    blurb: 'Clifftop golf where every right miss is the Pacific.',
    holes: holes([
      [4, 388, 9, 'S', 'sand'],
      [5, 527, 13, 'R', 'sand'],
      [4, 421, 3, 'R', 'ocean', 'The fairway tilts toward the cliff the whole way'],
      [3, 152, 17, 'S', 'ocean', 'Short but knee-knocking — nothing but surf long'],
      [4, 442, 1, 'R', 'ocean'],
      [4, 366, 11, 'L', 'sand'],
      [5, 561, 7, 'R', 'ocean', 'Three shots along the bluff, or two brave ones'],
      [3, 201, 15, 'S', 'sand'],
      [4, 409, 5, 'S', 'sand'],
      [4, 353, 16, 'L', 'sand'],
      [3, 176, 12, 'S', 'ocean'],
      [4, 431, 2, 'R', 'ocean', 'The chasm carry — the card turns here'],
      [5, 538, 10, 'L', 'sand'],
      [4, 397, 8, 'S', 'sand'],
      [4, 415, 4, 'R', 'ocean'],
      [3, 139, 18, 'S', 'sand'],
      [4, 380, 14, 'L', 'sand'],
      [5, 549, 6, 'R', 'ocean', 'Home along the point — birdie or heartbreak'],
    ]),
  },
  {
    slug: 'old-wick-links',
    name: 'Old Wick Links',
    location: 'East Lothian, Scotland',
    difficulty: 6,
    greens: 'Fast',
    wind: 18,
    blurb: 'Ancient linksland. Pot bunkers with names, wind with opinions.',
    holes: holes([
      [4, 358, 12, 'S', 'sand'],
      [4, 411, 4, 'S', 'sand'],
      [3, 164, 16, 'S', 'sand', 'Eleven bunkers ring a green the size of a kitchen'],
      [5, 512, 10, 'S', 'sand'],
      [4, 427, 2, 'R', 'sand', 'The Coffins — carry them or play backwards'],
      [4, 382, 8, 'S', 'none'],
      [3, 188, 14, 'S', 'sand'],
      [4, 443, 6, 'S', 'sand'],
      [5, 578, 18, 'S', 'sand', 'Downwind home — the easiest five on the coast'],
      [4, 391, 9, 'S', 'sand'],
      [3, 143, 17, 'S', 'sand'],
      [4, 462, 1, 'R', 'sand', 'The hardest two-shotter in the shire'],
      [4, 373, 13, 'L', 'none'],
      [5, 529, 11, 'S', 'sand'],
      [4, 404, 5, 'S', 'sand'],
      [3, 209, 7, 'S', 'sand', 'A long iron into an amphitheater of sod walls'],
      [4, 366, 15, 'S', 'none'],
      [5, 543, 3, 'R', 'sand', 'The burn crosses twice on the way home'],
    ]),
  },
  {
    slug: 'cypress-hollow',
    name: 'Cypress Hollow',
    location: 'Ponte Vedra, Florida',
    difficulty: 8,
    greens: 'Fast',
    wind: 9,
    blurb: 'Water on fourteen holes. Target golf, no bailouts.',
    holes: holes([
      [4, 401, 7, 'S', 'water'],
      [5, 533, 11, 'R', 'water'],
      [3, 172, 15, 'S', 'water'],
      [4, 448, 1, 'L', 'water', 'Water left, water long — the pros lay back here'],
      [4, 379, 13, 'R', 'sand'],
      [4, 421, 5, 'S', 'water'],
      [3, 194, 9, 'S', 'sand'],
      [5, 571, 3, 'L', 'water', 'Reachable, but the lake hugs the last ninety yards'],
      [4, 356, 17, 'S', 'none'],
      [4, 417, 6, 'R', 'water'],
      [5, 524, 12, 'S', 'sand'],
      [4, 438, 2, 'L', 'water'],
      [3, 161, 14, 'S', 'water', 'All carry over the lily pond'],
      [4, 391, 10, 'R', 'sand'],
      [4, 428, 4, 'S', 'water'],
      [5, 507, 16, 'R', 'water', 'A gambler’s five — water rings the peninsula green'],
      [3, 132, 18, 'S', 'water', 'The Island — no drop zone mercy today'],
      [4, 411, 8, 'L', 'water', 'Water down the left the whole way home'],
    ]),
  },
  {
    slug: 'copper-canyon',
    name: 'Copper Canyon',
    location: 'Scottsdale, Arizona',
    difficulty: 5,
    greens: 'Medium',
    wind: 6,
    blurb: 'Desert target golf. Green ribbons through red rock and cactus.',
    holes: holes([
      [4, 372, 11, 'S', 'sand'],
      [4, 419, 5, 'R', 'sand'],
      [3, 183, 13, 'S', 'sand'],
      [5, 547, 7, 'L', 'sand', 'A dry wash splits the layup zone'],
      [4, 402, 3, 'S', 'sand'],
      [4, 341, 17, 'R', 'none', 'Drivable if you flirt with the saguaros'],
      [3, 217, 9, 'S', 'sand'],
      [4, 433, 1, 'L', 'sand', 'The canyon squeezes the drive to a ribbon'],
      [5, 561, 15, 'S', 'sand'],
      [4, 386, 12, 'R', 'sand'],
      [3, 149, 18, 'S', 'none'],
      [4, 441, 2, 'S', 'sand'],
      [5, 528, 14, 'R', 'sand'],
      [4, 397, 8, 'L', 'sand'],
      [4, 424, 4, 'S', 'sand'],
      [3, 192, 16, 'S', 'sand'],
      [4, 409, 10, 'R', 'sand'],
      [5, 539, 6, 'L', 'sand', 'Sunset finisher between two mesas'],
    ]),
  },
  {
    slug: 'birchwood-national',
    name: 'Birchwood National',
    location: 'Grand Rapids, Michigan',
    difficulty: 6,
    greens: 'Firm',
    wind: 8,
    blurb: 'Cathedral pines, white sand, greens like upturned saucers.',
    holes: holes([
      [4, 411, 6, 'R', 'sand'],
      [5, 552, 12, 'L', 'sand', 'A long five through the pines'],
      [4, 384, 10, 'S', 'sand'],
      [3, 197, 8, 'S', 'sand'],
      [4, 439, 2, 'L', 'sand'],
      [4, 368, 16, 'S', 'none'],
      [5, 517, 14, 'R', 'sand'],
      [3, 158, 18, 'S', 'sand'],
      [4, 427, 4, 'S', 'sand'],
      [4, 393, 9, 'L', 'sand'],
      [3, 221, 5, 'S', 'sand', 'The crowned green repels anything timid'],
      [4, 446, 1, 'R', 'sand', 'The National — nothing but perfect will do'],
      [4, 375, 15, 'S', 'none'],
      [5, 568, 11, 'L', 'sand'],
      [4, 405, 7, 'R', 'sand'],
      [3, 166, 17, 'S', 'sand'],
      [4, 431, 3, 'S', 'sand'],
      [5, 536, 13, 'R', 'sand', 'The amphitheater finish under the clubhouse oaks'],
    ]),
  },
  {
    slug: 'millbrook-valley',
    name: 'Millbrook Valley',
    location: 'Hollow Creek, Tennessee',
    difficulty: 7,
    greens: 'Fast',
    wind: 8,
    blurb: 'A mountain valley course where the creek is always listening.',
    holes: holes([
      [4, 469, 3, 'R', 'sand'],
      [3, 231, 7, 'S', 'sand'],
      [4, 353, 17, 'L', 'water'],
      [5, 546, 11, 'R', 'water', 'The creek crosses twice before the green'],
      [3, 187, 9, 'S', 'water'],
      [4, 445, 13, 'S', 'sand'],
      [4, 378, 15, 'R', 'water'],
      [5, 568, 5, 'L', 'sand'],
      [4, 433, 1, 'S', 'water', 'The valley’s meanest four — creek left, wall right'],
      [4, 392, 14, 'R', 'sand'],
      [5, 531, 12, 'L', 'water'],
      [3, 169, 16, 'S', 'water', 'An uphill carry to a nearly blind shelf'],
      [4, 408, 6, 'S', 'sand'],
      [4, 297, 18, 'R', 'water', 'Drivable, but the pond guards the hero line'],
      [4, 481, 2, 'R', 'water'],
      [4, 417, 10, 'L', 'sand'],
      [3, 195, 8, 'S', 'water'],
      [5, 512, 4, 'S', 'water', 'Break-par-or-break-down finisher over the mill pond'],
    ]),
  },
]

export function courseBySlug(slug: string): CourseSpec | undefined {
  return COURSES.find((c) => c.slug === slug)
}
