/**
 * GENERATED by scripts/gen-play-ratings.ts — do not edit by hand.
 * Regenerate with `pnpm gen:ratings` whenever the engine odds/resolution or
 * the course library change (the numbers are simulation-derived).
 *
 * A course's Play Rating is an ABSOLUTE 1–10 measure of how hard the course
 * actually plays — a competent ("smart" policy) golfer's average score to par
 * over 4000 simulated rounds, bucketed by fixed thresholds. It is display-only
 * and completely separate from the internal `difficulty` knob that feeds the
 * odds engine (that one still carries a hidden daily ±1 jitter).
 */
export interface PlayRatingMeta {
  /** simulated rounds per course */
  rounds: number
  /** decision policy used as the reference golfer */
  policy: string
  /** avg-to-par → rating cutoffs, highest first: [minIndex, rating] */
  cutoffs: [number, number][]
}

export const PLAY_RATING_META: PlayRatingMeta = {
  rounds: 4000,
  policy: 'smart',
  cutoffs: [[3, 10], [2.2, 9], [1.7, 8], [1.4, 7], [1, 6], [0.6, 5], [0.2, 4], [-0.2, 3], [-0.6, 2]],
}

/** slug → Play Rating (1–10). */
export const PLAY_RATINGS: Record<string, number> = {
  'pebble-beach': 5,
  'st-andrews-old': 5,
  'augusta-national': 6,
  'tpc-sawgrass': 9,
  'harbour-town': 7,
  'carnoustie': 8,
  'copper-canyon': 1,
  'royal-portrush-dunluce': 9,
  'cypress-point': 3,
  'whistling-straits': 9,
  'tpc-potomac': 8,
  'gullwing-point': 4,
  'seminole': 8,
  'birchwood-national': 1,
  'torrey-pines-south': 6,
  'pacific-dunes': 5,
  'pine-valley': 10,
  'bandon-dunes': 6,
  'muirfield': 5,
  'quail-hollow': 8,
  'shinnecock-hills': 9,
  'millbrook-valley': 5,
  'lacc-north': 7,
  'cabot-links': 4,
  'oakmont': 9,
  'camargo': 4,
  'doral-blue-monster': 9,
  'erin-hills': 5,
  'winged-foot-west': 8,
  'national-golf-links': 5,
  'the-country-club': 7,
  'whispering-pines': 6,
  'royal-birkdale': 9,
  'merion-east': 4,
  'kiawah-ocean': 10,
  'arcadia-bluffs': 4,
  'prairie-dunes': 9,
  'pinehurst-no2': 8,
  'riviera': 7,
  'cypress-hollow': 6,
  'royal-melbourne': 5,
  'bethpage-black': 9,
  'royal-dornoch': 6,
  'royal-troon': 7,
  'paynes-valley': 4,
  'aronimink': 7,
  'muirfield-village': 9,
  'old-wick-links': 2,
  'chambers-bay': 7,
  'cobblestone-creek': 5,
  'the-swing': 1,
  'palm-beach-par-3': 8,
  'kings-creek': 4,
  'the-dogleg': 5,
}

/** avg score-to-par measured per course, kept for the methodology disclaimer. */
export const PLAY_INDEX: Record<string, number> = {
  'pebble-beach': 0.665,
  'st-andrews-old': 0.620,
  'augusta-national': 1.034,
  'tpc-sawgrass': 2.780,
  'harbour-town': 1.461,
  'carnoustie': 1.740,
  'copper-canyon': -1.020,
  'royal-portrush-dunluce': 2.238,
  'cypress-point': 0.098,
  'whistling-straits': 2.456,
  'tpc-potomac': 1.984,
  'gullwing-point': 0.554,
  'seminole': 2.050,
  'birchwood-national': -0.804,
  'torrey-pines-south': 1.373,
  'pacific-dunes': 0.887,
  'pine-valley': 3.307,
  'bandon-dunes': 1.141,
  'muirfield': 0.703,
  'quail-hollow': 2.154,
  'shinnecock-hills': 2.711,
  'millbrook-valley': 0.796,
  'lacc-north': 1.566,
  'cabot-links': 0.580,
  'oakmont': 2.905,
  'camargo': 0.430,
  'doral-blue-monster': 2.947,
  'erin-hills': 0.919,
  'winged-foot-west': 1.721,
  'national-golf-links': 0.609,
  'the-country-club': 1.463,
  'whispering-pines': 1.262,
  'royal-birkdale': 2.499,
  'merion-east': 0.513,
  'kiawah-ocean': 4.112,
  'arcadia-bluffs': 0.542,
  'prairie-dunes': 2.207,
  'pinehurst-no2': 1.780,
  'riviera': 1.652,
  'cypress-hollow': 1.037,
  'royal-melbourne': 0.837,
  'bethpage-black': 2.221,
  'royal-dornoch': 1.070,
  'royal-troon': 1.447,
  'paynes-valley': 0.293,
  'aronimink': 1.520,
  'muirfield-village': 2.870,
  'old-wick-links': -0.454,
  'chambers-bay': 1.457,
  'cobblestone-creek': 0.761,
  'the-swing': -1.090,
  'palm-beach-par-3': 2.187,
  'kings-creek': 0.526,
  'the-dogleg': 0.653,
}
