/**
 * GENERATED by scripts/gen-play-ratings.ts — do not edit by hand.
 * Regenerate with `pnpm gen:ratings` whenever the engine odds/resolution or
 * the course library change (the numbers are simulation-derived).
 *
 * A course's Play Rating is an ABSOLUTE 1–10 measure of how hard the course
 * actually plays — a competent ("smart" policy) golfer's average score to par
 * over 4000 simulated rounds, bucketed by fixed thresholds. It is display-only
 * and completely separate from the internal `difficulty` knob that feeds the
 * odds engine (that one still carries a hidden daily ±1 jitter).
 */
export interface PlayRatingMeta {
  /** simulated rounds per course */
  rounds: number
  /** decision policy used as the reference golfer */
  policy: string
  /** avg-to-par → rating cutoffs, highest first: [minIndex, rating] */
  cutoffs: [number, number][]
}

export const PLAY_RATING_META: PlayRatingMeta = {
  rounds: 4000,
  policy: 'smart',
  cutoffs: [[3, 10], [2.2, 9], [1.7, 8], [1.4, 7], [1, 6], [0.6, 5], [0.2, 4], [-0.2, 3], [-0.6, 2]],
}

/** slug → Play Rating (1–10). */
export const PLAY_RATINGS: Record<string, number> = {
  'pebble-beach': 5,
  'st-andrews-old': 5,
  'augusta-national': 6,
  'tpc-sawgrass': 10,
  'harbour-town': 7,
  'carnoustie': 8,
  'copper-canyon': 1,
  'royal-portrush-dunluce': 8,
  'cypress-point': 1,
  'whistling-straits': 8,
  'tpc-potomac': 8,
  'gullwing-point': 5,
  'seminole': 8,
  'birchwood-national': 1,
  'torrey-pines-south': 9,
  'pacific-dunes': 7,
  'pine-valley': 6,
  'bandon-dunes': 8,
  'muirfield': 5,
  'quail-hollow': 7,
  'shinnecock-hills': 9,
  'millbrook-valley': 6,
  'lacc-north': 6,
  'cabot-links': 6,
  'oakmont': 9,
  'camargo': 4,
  'doral-blue-monster': 8,
  'erin-hills': 6,
  'winged-foot-west': 8,
  'national-golf-links': 4,
  'the-country-club': 7,
  'whispering-pines': 6,
  'royal-birkdale': 9,
  'merion-east': 4,
  'kiawah-ocean': 10,
  'arcadia-bluffs': 5,
  'prairie-dunes': 9,
  'pinehurst-no2': 8,
  'riviera': 8,
  'cypress-hollow': 7,
  'royal-melbourne': 5,
  'bethpage-black': 9,
  'royal-dornoch': 6,
  'royal-troon': 7,
  'paynes-valley': 4,
  'aronimink': 7,
  'muirfield-village': 10,
  'old-wick-links': 2,
  'chambers-bay': 7,
  'cobblestone-creek': 5,
  'the-swing': 1,
  'palm-beach-par-3': 8,
}

/** avg score-to-par measured per course, kept for the methodology disclaimer. */
export const PLAY_INDEX: Record<string, number> = {
  'pebble-beach': 0.850,
  'st-andrews-old': 0.656,
  'augusta-national': 1.184,
  'tpc-sawgrass': 3.141,
  'harbour-town': 1.668,
  'carnoustie': 2.073,
  'copper-canyon': -0.991,
  'royal-portrush-dunluce': 2.092,
  'cypress-point': -0.613,
  'whistling-straits': 1.901,
  'tpc-potomac': 1.721,
  'gullwing-point': 0.656,
  'seminole': 2.048,
  'birchwood-national': -0.736,
  'torrey-pines-south': 2.397,
  'pacific-dunes': 1.571,
  'pine-valley': 1.367,
  'bandon-dunes': 1.731,
  'muirfield': 0.960,
  'quail-hollow': 1.599,
  'shinnecock-hills': 2.441,
  'millbrook-valley': 1.085,
  'lacc-north': 1.341,
  'cabot-links': 1.241,
  'oakmont': 2.461,
  'camargo': 0.483,
  'doral-blue-monster': 2.117,
  'erin-hills': 1.010,
  'winged-foot-west': 1.813,
  'national-golf-links': 0.599,
  'the-country-club': 1.523,
  'whispering-pines': 1.389,
  'royal-birkdale': 2.585,
  'merion-east': 0.597,
  'kiawah-ocean': 4.323,
  'arcadia-bluffs': 0.645,
  'prairie-dunes': 2.300,
  'pinehurst-no2': 1.864,
  'riviera': 1.721,
  'cypress-hollow': 1.562,
  'royal-melbourne': 0.931,
  'bethpage-black': 2.329,
  'royal-dornoch': 1.106,
  'royal-troon': 1.613,
  'paynes-valley': 0.405,
  'aronimink': 1.576,
  'muirfield-village': 3.100,
  'old-wick-links': -0.459,
  'chambers-bay': 1.548,
  'cobblestone-creek': 0.826,
  'the-swing': -1.090,
  'palm-beach-par-3': 2.071,
}
