/**
 * GENERATED by scripts/gen-play-ratings.ts — do not edit by hand.
 * Regenerate with `pnpm gen:ratings` whenever the engine odds/resolution or
 * the course library change (the numbers are simulation-derived).
 *
 * A course's Play Rating is an ABSOLUTE 1–10 measure of how hard the course
 * actually plays — a competent ("smart" policy) golfer's average score to par
 * over 4000 simulated rounds, bucketed by fixed thresholds. It is display-only
 * and completely separate from the internal `difficulty` knob that feeds the
 * odds engine (that one still carries a hidden daily ±1 jitter).
 */
export interface PlayRatingMeta {
  /** simulated rounds per course */
  rounds: number
  /** decision policy used as the reference golfer */
  policy: string
  /** avg-to-par → rating cutoffs, highest first: [minIndex, rating] */
  cutoffs: [number, number][]
}

export const PLAY_RATING_META: PlayRatingMeta = {
  rounds: 4000,
  policy: 'smart',
  cutoffs: [[3, 10], [2.2, 9], [1.7, 8], [1.4, 7], [1, 6], [0.6, 5], [0.2, 4], [-0.2, 3], [-0.6, 2]],
}

/** slug → Play Rating (1–10). */
export const PLAY_RATINGS: Record<string, number> = {
  'pebble-beach': 5,
  'st-andrews-old': 5,
  'augusta-national': 6,
  'tpc-sawgrass': 10,
  'harbour-town': 8,
  'carnoustie': 8,
  'copper-canyon': 1,
  'royal-portrush-dunluce': 8,
  'cypress-point': 1,
  'whistling-straits': 8,
  'tpc-potomac': 7,
  'gullwing-point': 5,
  'seminole': 8,
  'birchwood-national': 1,
  'torrey-pines-south': 9,
  'pacific-dunes': 7,
  'pine-valley': 6,
  'bandon-dunes': 7,
  'muirfield': 5,
  'quail-hollow': 7,
  'shinnecock-hills': 9,
  'millbrook-valley': 6,
  'lacc-north': 6,
  'cabot-links': 6,
  'oakmont': 9,
  'camargo': 4,
  'doral-blue-monster': 8,
  'erin-hills': 5,
  'winged-foot-west': 8,
  'national-golf-links': 4,
  'the-country-club': 7,
  'whispering-pines': 6,
  'royal-birkdale': 9,
  'merion-east': 4,
  'kiawah-ocean': 10,
  'arcadia-bluffs': 4,
  'prairie-dunes': 9,
  'pinehurst-no2': 8,
  'riviera': 8,
  'cypress-hollow': 7,
  'royal-melbourne': 5,
  'bethpage-black': 9,
  'royal-dornoch': 6,
  'royal-troon': 7,
  'paynes-valley': 4,
  'aronimink': 7,
  'muirfield-village': 10,
  'old-wick-links': 2,
  'chambers-bay': 7,
  'cobblestone-creek': 5,
  'the-swing': 1,
  'palm-beach-par-3': 8,
}

/** avg score-to-par measured per course, kept for the methodology disclaimer. */
export const PLAY_INDEX: Record<string, number> = {
  'pebble-beach': 0.832,
  'st-andrews-old': 0.675,
  'augusta-national': 1.159,
  'tpc-sawgrass': 3.091,
  'harbour-town': 1.941,
  'carnoustie': 2.060,
  'copper-canyon': -0.994,
  'royal-portrush-dunluce': 2.080,
  'cypress-point': -0.623,
  'whistling-straits': 1.852,
  'tpc-potomac': 1.692,
  'gullwing-point': 0.644,
  'seminole': 2.039,
  'birchwood-national': -0.744,
  'torrey-pines-south': 2.368,
  'pacific-dunes': 1.544,
  'pine-valley': 1.335,
  'bandon-dunes': 1.668,
  'muirfield': 0.964,
  'quail-hollow': 1.574,
  'shinnecock-hills': 2.414,
  'millbrook-valley': 1.012,
  'lacc-north': 1.309,
  'cabot-links': 1.216,
  'oakmont': 2.435,
  'camargo': 0.455,
  'doral-blue-monster': 2.064,
  'erin-hills': 0.981,
  'winged-foot-west': 1.824,
  'national-golf-links': 0.594,
  'the-country-club': 1.488,
  'whispering-pines': 1.358,
  'royal-birkdale': 2.552,
  'merion-east': 0.572,
  'kiawah-ocean': 4.258,
  'arcadia-bluffs': 0.596,
  'prairie-dunes': 2.296,
  'pinehurst-no2': 1.874,
  'riviera': 1.702,
  'cypress-hollow': 1.514,
  'royal-melbourne': 0.898,
  'bethpage-black': 2.330,
  'royal-dornoch': 1.083,
  'royal-troon': 1.579,
  'paynes-valley': 0.379,
  'aronimink': 1.553,
  'muirfield-village': 3.076,
  'old-wick-links': -0.451,
  'chambers-bay': 1.503,
  'cobblestone-creek': 0.798,
  'the-swing': -1.132,
  'palm-beach-par-3': 1.957,
}
