/**
 * Auth email template generator (build-time tool — never runs in the app).
 *
 * Renders the Supabase Auth emails defined in
 * supabase/functions/_shared/auth-emails.ts out to supabase/templates/*.html so
 * the exact HTML that gets pushed to the project is reviewable in a diff.
 *
 * Run:  pnpm gen:email-templates
 *       pnpm gen:email-templates --check   # fail if the files are stale (CI)
 *
 * Push the generated files with `pnpm push:email-templates` — see that script
 * for the auth-config PATCH.
 */
import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { AUTH_EMAILS } from '../supabase/functions/_shared/auth-emails.ts'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = resolve(root, 'supabase/templates')
const check = process.argv.includes('--check')

mkdirSync(outDir, { recursive: true })

let stale = 0
for (const email of AUTH_EMAILS) {
  const path = resolve(outDir, email.file)
  // The subject lives in auth config, not in the file — keep it visible to
  // anyone reading the HTML so a copy change never lands half-done.
  const contents = `<!-- GENERATED by pnpm gen:email-templates — edit supabase/functions/_shared/auth-emails.ts, not this file.
     Supabase auth config keys: mailer_templates_${email.key}_content
                                mailer_subjects_${email.key} = ${email.subject}
-->
${email.html}
`
  const prev = existsSync(path) ? readFileSync(path, 'utf8') : null
  if (prev === contents) {
    console.log(`  ok     ${email.file}`)
    continue
  }
  if (check) {
    console.error(`  STALE  ${email.file}`)
    stale++
    continue
  }
  writeFileSync(path, contents)
  console.log(`  wrote  ${email.file}`)
}

if (stale) {
  console.error(`\n${stale} template(s) out of date — run: pnpm gen:email-templates`)
  process.exit(1)
}
